[build]
  command = "npm run build"
  publish = "dist"
  commandOrigin = "config"
  publishOrigin = "config"

[build.environment]
  CI = "true"

[[redirects]]
from = "/"*
to = "/index.html"
status = 200